### PR TITLE
Updates Dockerfile to use debian wheezy

### PR DESCRIPTION
**Pull request by rolandpoulter**
* Replaces `apk` commands with `apt-get`
* Adds `.dockerignore` file to speed up docker builds

### CODE REVIEW

**Comment by rolandpoulter** [comment]
This PR requires changes to `on-core`, `on-taskgraph`, and `on-http` Dockerfiles.
https://github.com/RackHD/on-taskgraph/pull/171
https://github.com/RackHD/on-http/pull/466
https://github.com/RackHD/on-core/pull/210

**Comment by pscharla** [comment]
:+1:

**Comment by pscharla** [comment]
@RackHD/corecommitters Please review - updates for switching away from Alpine (due to missing packages) to debian

**Comment by pscharla** [comment]
@RackHD/corecommitters This one looks ready to merge

**Pull request merged**
