### PR TITLE
change ucs jobs to pass auth info via headers

### PR DESCRIPTION
**Pull request by geoff-reid**
jenkins: depends on https://github.com/RackHD/ucs-service/pull/14

### CODE REVIEW

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by PengTian0** [comment]
BUILD [on-tasks #6](http://147.178.202.18//blue/organizations/jenkins/on-tasks/detail/on-tasks/6/pipeline) : FAILURE

<details>
<summary>BUILD on-tasks #6  Error Logs  &#9660;</summary>Test Name: catalog-lsall-spec.js task-data expected properties should have valid default option values
Error Details: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Stack Trace: Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (node_modules/on-core/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

Test Name: Redfish Managers should return the RackHD manager
Error Details: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Stack Trace: Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Test Name: Redfish Managers "after all" hook: stop HTTP server
Error Details: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Stack Trace: Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Test Name: Redfish Schemas "before all" hook: start HTTP server
Error Details: Connection is already registered
Stack Trace: AdapterError: Connection is already registered
    at Object.module.exports.adapter.registerConnection (node_modules/on-core/node_modules/sails-mongo/lib/adapter.js:86:60)
    at node_modules/on-core/node_modules/waterline/lib/waterline.js:203:29
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Array.async.auto.registerConnections (node_modules/on-core/node_modules/waterline/lib/waterline.js:176:13)
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at Waterline.initialize (node_modules/on-core/node_modules/waterline/lib/waterline.js:121:9)
    at node_modules/on-core/lib/services/waterline.js:96:26
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (node_modules/on-core/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (node_modules/on-core/node_modules/bluebird/js/main/promise.js:71:37)
    at WaterlineServiceFactory.WaterlineService.initService (node_modules/on-core/lib/services/waterline.js:42:16)
    at node_modules/on-core/lib/services/waterline.js:120:29
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (node_modules/on-core/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

Test Name: Redfish Schemas "after all" hook: stop HTTP server
Error Details: Cannot read property 'validate' of undefined
Stack Trace: TypeError: Cannot read property 'validate' of undefined
    at Context.&lt;anonymous&gt; (spec/lib/api/redfish-1.0/schemas-spec.js:36:18)

Test Name: Redfish Session Service "before all" hook: start HTTP server
Error Details: Connection is already registered
Stack Trace: AdapterError: Connection is already registered
    at Object.module.exports.adapter.registerConnection (node_modules/on-core/node_modules/sails-mongo/lib/adapter.js:86:60)
    at node_modules/on-core/node_modules/waterline/lib/waterline.js:203:29
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Array.async.auto.registerConnections (node_modules/on-core/node_modules/waterline/lib/waterline.js:176:13)
    at node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (node_modules/on-core/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at Waterline.initialize (node_modules/on-core/node_modules/waterline/lib/waterline.js:121:9)
    at node_modules/on-core/lib/services/waterline.js:96:26
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (node_modules/on-core/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (node_modules/on-core/node_modules/bluebird/js/main/promise.js:71:37)
    at WaterlineServiceFactory.WaterlineService.initService (node_modules/on-core/lib/services/waterline.js:42:16)
    at node_modules/on-core/lib/services/waterline.js:120:29
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (node_modules/on-core/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

Test Name: Redfish Session Service "after all" hook: stop HTTP server
Error Details: Cannot read property 'validate' of undefined
Stack Trace: TypeError: Cannot read property 'validate' of undefined
    at Context.&lt;anonymous&gt; (spec/lib/api/redfish-1.0/session-service-spec.js:97:18)

</details>

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
BUILD [on-tasks #7](http://147.178.202.18//blue/organizations/jenkins/on-tasks/detail/on-tasks/7/pipeline) : FAILURE

**Comment by geoff-reid** [comment]
@keedya @tannoa2 @uppalk1 @RackHD/corecommitters

**Pull request merged**
