### PR TITLE
Remove the IPMI password from AMQP and log messages.

### PR DESCRIPTION
**Pull request by jlongever**
Resolve issues: 
https://github.com/RackHD/RackHD/issues/217
https://github.com/RackHD/RackHD/issues/216

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by jlongever** [comment]
Realized the password is still in the error message, updating now.

**Comment by zyoung51** [comment]
+1

**Comment by jlongever** [comment]
test this please

**Comment by brianparry** [comment]
::+1:

**Pull request merged**
