### PR TITLE
Added timeout into fru parser spec code

### PR DESCRIPTION
**Pull request by pscharla**
@benbp @yyscamper : Added 5s timeout to allow Jenkins build jobs to complete succesfully

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
Hi @pscharla : I think we should try to find out the reason why this test suite need so much time to complete instead of extending the test  time to hide the real problem.
I checked the number of test cases within this test suite is only one, and the [sample file] (https://github.com/RackHD/on-tasks/blob/master/spec%2Flib%2Futils%2Fjob-utils%2Fsamplefiles%2Fquanta_fru.txt)  is very small, but it shouldn't require so much time to run.

I tested in my RackHD instance, the unit test will success:
```
onrack@~/src/on-tasks> mocha spec/lib/utils/job-utils/fru-parser-spec.js -R spec --require spec/helper.js


  ipmi fru Task Parser
DEPRECATION: Services.Configuration - Attempting to access color - prior to configuration service being started /node_modules/on-core/lib/services/argument-handler.js:38
DEPRECATION: Services.Configuration - Attempting to access logColorEnable - prior to configuration service being started /node_modules/on-core/lib/services/argument-handler.js:38
    ✓ should parse `ipmitool fru` output


  1 passing (676ms)
```

Is your test machine's performance is very low?

**Comment by yyscamper** [comment]
Meanwhile, I suggest to squeeze such a simple change to one commit.

**Comment by pscharla** [comment]
The build failures are seen in Jenkins in both the packages build job for on-tasks and the manifest build job where you see this error message:

timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

So it looks like it has 2s timeout but even exceeding that due to what @benbp calls "Jenkins perf issues".  I'm guessing this is not seen in the Travis build environment.

**Comment by heckj** [comment]
I'm guessing this is happening on heavily loaded virtual machines that are the jenkins slaves internally

**Comment by pscharla** [comment]
@yyscamper Sorry - newbie to js, so forgot the semicolon first time around.  I assume you are talking about squashing commits.  Any benefit to doing that now that the commits are already pushed up?

**Comment by heckj** [comment]
@pscharla yeah, it's a fairly common request to keep the log of what the changes were a little tighter and cleaner. If you want help walking through a rebase, more than happy to do so, give me a holler on slack or call and I can walk you through it.

There's also pretty decent documentation:
* https://help.github.com/articles/about-git-rebase/
* https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i
* https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by pscharla** [comment]
Just performed the squash with the help of @heckj.  However, as part of the process created branch of my fork and put the changes there.  Will kill this PR and open a new one pointing to the branch.

**Pull request closed without merging**
