### PR TITLE
Fix lookup Ip by Mac address in racadm

### PR DESCRIPTION
**Pull request by keedya**
fix for issue: https://github.com/RackHD/RackHD/issues/352

### CODE REVIEW

**Comment by keedya** [comment]
@brianparry @ytjohn @RackHD/corecommitters @zyoung51 @jlongever @dalebremner @BillyAbildgaard @srinia6

**Comment by keedya** [comment]
@here unit tests need to be fixed as well

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by srinia6** [comment]
+1

**Pull request merged**
