### PR TITLE
Remove devDependency from task annotation script

### PR DESCRIPTION
**Pull request by WangWinson**
resolves https://github.com/RackHD/RackHD/issues/357
`on-core/spec/helper` has devDependency which will not be installed in production env. So remove it will solve the issue

@RackHD/corecommitters @cgx027 @iceiilin @pengz1

### CODE REVIEW

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by michaelsteven** [comment]
@yyscamper there is a new error when the ansible remoterepo Generate hosted task documentation runs.  "Cannot find module 'on-core/node-modules/glob'"

glob

**Comment by WangWinson** [comment]
Thanks @michaelsteven to reporting the issue. Though, that looks wired. Is the log you showed happened during packer build ?

**Comment by michaelsteven** [comment]
Yes, this is from my Bamboo server which has a job to make an OVA that runs the packer vmware builder to build a Ubuntu 16.04 vm, and runs the ansible-local provisioner runs the rackhd_local playbook.  I try to post better output if you would like.

**Comment by michaelsteven** [comment]
build	03-Aug-2016 22:29:02	[0;32m    build-113: TASK [remoterepos : Npm install apidoc] ****************************************[0m
build	03-Aug-2016 22:29:08	[0;32m    build-113: [0;33mchanged: [127.0.0.1][0m[0m
build	03-Aug-2016 22:29:08	[0;32m    build-113:[0m
build	03-Aug-2016 22:29:08	[0;32m    build-113: TASK [remoterepos : Render 1.1 API docs for local reference] *******************[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113: [0;33mchanged: [127.0.0.1][0m[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113:[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113: TASK [remoterepos : Generate hosted task documentation] ************************[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113: [0;31mfatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "npm run taskdoc", "delta": "0:00:00.552275", "end": "2016-08-04 03:29:09.713680", "failed": true, "rc": 1, "start": "2016-08-04 03:29:09.161405", "stderr": "module.js:327\n    throw err;\n    ^\n\nError: Cannot find module 'on-core/node_modules/glob'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.Module._load (module.js:276:25)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/home/devuser/src/on-http/node_modules/on-tasks/task-annotation-generator.js:227:16)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Function.Module.runMain (module.js:441:10)\ncat: task_doc_data.json: No such file or directory\nmv: cannot stat './node_modules/on-tasks/task_doc_data.json': No such file or directory\n\nnpm ERR! Linux 4.4.0-31-generic\nnpm ERR! argv \"/usr/bin/nodejs\" \"/usr/bin/npm\" \"run\" \"taskdoc\"\nnpm ERR! node v4.4.7\nnpm ERR! npm  v2.15.8\nnpm ERR! code ELIFECYCLE\nnpm ERR! on-http@0.0.0 taskdoc: `./install-task-doc.sh`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the on-http@0.0.0 taskdoc script './install-task-doc.sh'.\nnpm ERR! This is most likely a problem with the on-http package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     ./install-task-doc.sh\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs on-http\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR! \nnpm ERR!     npm owner ls on-http\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /home/devuser/src/on-http/npm-debug.log", "stdout": "\n> on-http@0.0.0 taskdoc /home/devuser/src/on-http\n> ./install-task-doc.sh", "stdout_lines": ["", "> on-http@0.0.0 taskdoc /home/devuser/src/on-http", "> ./install-task-doc.sh"], "warnings": []}[0m[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113:[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113: PLAY RECAP *********************************************************************[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113: [0;31m127.0.0.1[0m                  : [0;32mok[0m[0;32m=[0m[0;32m27[0m   [0;33mchanged[0m[0;33m=[0m[0;33m23[0m   unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m[0m
build	03-Aug-2016 22:29:09	[0;32m    build-113:[0m
build	03-Aug-2016 22:29:10	[1;32m==> build-113: Stopping virtual machine...[0m
build	03-Aug-2016 22:29:10	[1;32m==> build-113: Destroying virtual machine...[0m
build	03-Aug-2016 22:29:11	[1;31mBuild 'build-113' errored: Error executing Ansible: Non-zero exit status: 2[0m

**Pull request merged**
