### PR TITLE
Changes $taskTimeout to _taskTimeout

### PR DESCRIPTION
**Pull request by rolandpoulter**
Fixes: https://github.com/RackHD/RackHD/issues/258

### CODE REVIEW

**Comment by heckj** [comment]
+1

**Comment by benbp** [comment]
Needs a doc update too: https://github.com/RackHD/docs/blob/e747091db55624a040cf0019b63ab16c70dd56ae/docs/rackhd/tasks.rst#task-timeouts

**Comment by benbp** [comment]
CC @RackHD/corecommitters @yyscamper

**Comment by benbp** [comment]
👍

**Comment by rolandpoulter** [comment]
Updated docs: https://github.com/RackHD/docs/pull/290

**Comment by benbp** [comment]
test this please

**Comment by yyscamper** [comment]
:+1: 

I still need to update my JSON-schema definition.

**Comment by yyscamper** [comment]
I don't know why the travis ci refuses to test this PR, @rolandpoulter could you please recommit your change and trigger the travisci?

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
@rolandpoulter : could you please recommit your code change so that the travisci can be triggered again.

**Comment by panpan0000** [comment]
test this please

**Pull request merged**
