### PR TITLE
[RAC-6176] refactor WsmanTool and wsman-related jobs

### PR DESCRIPTION
**Pull request by lanchongyizu**
**Background**

As the RACADM replacement work squad, we need to work on common wsman-tools functionality, so that everyone can focus on their own tasks.

**Details**

1) create a base job for wsman-related jobs, which handles both syncRequest and asyncRequest
2) refactor JobUtils.WsmanTool
3) refine the code for wsman-related jobs

**Reviewers**

@RackHD/corecommitters @nortonluo @yaolingling

### CODE REVIEW

**Comment by lanchongyizu** [comment]
test this please.

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by nortonluo** [comment]
Seems there is many tab instead of space

**Pull request merged**
