### PR TITLE
Update ansible job util

### PR DESCRIPTION
**Pull request by keedya**
- New rackhd.py is now merged to ansible repo : https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/rackhd.py
- Support for args --list and --host are requirements in ansible inventory scripts

### CODE REVIEW

**Comment by keedya** [comment]
@benbp @zyoung51 @jlongever

**Comment by benbp** [comment]
+1

**Comment by iceiilin** [comment]
+1

**Comment by jlongever** [comment]
test this please

**Comment by zyoung51** [comment]
+1

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
