### PR TITLE
add smbRepo parameter to the windows install task

### PR DESCRIPTION
**Pull request by tannoa2**

### CODE REVIEW

**Comment by keedya** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Pull request merged**
