### PR TITLE
IME-63 Adding switchDevices/postInstallCommands in the options list o…

### PR DESCRIPTION
**Pull request by manfrednde**
…f install esx task

for the 1.2 branch.

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by manfrednde** [comment]
This change will allow switch devices to be set up  during Esx bootstrap  using 1.2 branch
 @RackHD/corecommitters @jimturnquist @johren @derrickostertag

**Comment by derrickostertag** [comment]
+1

**Comment by yyscamper** [comment]
The jenkins error is expected as it doesn't support build on branch.

**Pull request merged**
