### PR TITLE
changing download-file to use 2.0 api syntax

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
updating download-files task to use 2.0 api syntax

@RackHD/corecommitters @geoff-reid @srinia6 @dalebremner

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by BillyAbildgaard** [comment]
resolves https://github.com/RackHD/on-tasks/issues/351

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by BillyAbildgaard** [comment]
@zyoung51 :)

**Comment by anhou** [comment]
:+1:

**Pull request merged**
