### PR TITLE
Correct options in task

### PR DESCRIPTION
**Pull request by keedya**
@brianparry @tannoa2 @jlongever @zyoung51

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by anhou** [comment]
@keedya just noticed that there's no unit test for this file under spec/lib/task-data/tasks/  :+1: with a supplement

**Comment by keedya** [comment]
@anhou there is unit test for this file; remove-bmc-credentials-spec.js under spec/lib/task-data.

**Comment by anhou** [comment]
@keedya Thanks for pointing out. could you help let file name be consistent in this PR? either 'rm' or 'remove".  it will help a lot to identify the unit test file quickly when other guys update unit tests.

**Comment by keedya** [comment]
@anhou, PR updated!

**Comment by anhou** [comment]
@keedya Thanks!, but It seems that remove-bmc-credentials-spec.js is still there? not see a rename change in file change.

**Comment by keedya** [comment]
@anhou Sorry about that. Should be all set now!!

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
