### PR TITLE
Fix task cancel method to properly handle timeout cancellations

### PR DESCRIPTION
**Pull request by johren**
Recreated PRs for ODR-273 fix on 1.0.0 branch. Needed for 1.0.5 release.

### CODE REVIEW

**Comment by johren** [comment]
Manfred is currently running this through a test on his stack.

**Comment by johren** [comment]
@benbp @yyscamper @anhou Please review to make sure I recreated this correctly.

Please DO NOT MERGE until testing is complete. Thanks!

**Comment by benbp** [comment]
:+1:

**Comment by yyscamper** [comment]
Actually, this is a duplicated PR, @benbp has opened the same PR before. We closed that PR because at that time we think the ODR-273 fix doesn't need be included in 1.0.0 branch.

Code change is same, so :+1:

**Comment by johren** [comment]
Testing was successful.  @benbp @yyscamper @anhou @brianparry or @jlongever, please merge these three PRs at the same time as soon as possible:
https://github.com/RackHD/on-tasks/pull/84
https://github.com/RackHD/on-core/pull/40
https://github.com/RackHD/on-taskgraph/pull/35

Thanks!

**Pull request merged**
