### PR TITLE
Get ssh settings from ibm model

### PR DESCRIPTION
**Pull request by dalebremner**
@RackHD/corecommitters @srinia6 @geoff-reid @BillyAbildgaard 

depends on https://github.com/RackHD/on-core/pull/222

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by dalebremner** [comment]
test this please

**Comment by changev** [comment]
Jenkins: depends on https://github.com/RackHD/on-core/pull/218

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
@dalebremner now RackHD jenkins doesn't support PR to **#feature-branch#** which is just exists in one repo.

In this PR feature/ibms just exists in on-tasks and on-core, but not other repos. So test will fail.

It will be another story to support PR to **#feature-branch#**  which is just exists in only one repo.
@panpan0000 @amymullins

**Comment by dalebremner** [comment]
Ok thanks @changev

**Comment by yyscamper** [comment]
@dalebremner : why not open such PR to master branch?

**Comment by dalebremner** [comment]
@yyscamper We decided to use a feature branch for this sprint so that we would have more time to discuss this change with the group, and to update the migration script.

**Comment by amymullins** [comment]
@yyscamper from a post in the RackHD CC channel on 10/6:

_@rackhd-team The stryker team is working on some changes that will require database migration.  We're not ready to merge these changes to master, but we want to get some PRs up to get eyes on the code.  Does anyone object to me adding a feature branch in the RackHD project for this?  That would allow us to submit PRs against this feature branch and then merge to master later when all the pieces are ready._

2 more stories need to be complete prior to merging in to the master branch: https://www.pivotaltracker.com/story/show/128227121 and https://www.pivotaltracker.com/story/show/130198079

**Pull request merged**
