### PR TITLE
Fix macaddress missing in lookup which lead to duplicated discovery

### PR DESCRIPTION
**Pull request by anhou**
Fix https://rackhd.atlassian.net/browse/RAC-490

### CODE REVIEW

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by pengz1** [comment]
+1

**Pull request merged**
