### PR TITLE
[RAC-5456] add taskName and graphName into on-taskgraph log

### PR DESCRIPTION
**Pull request by yaolingling**
**Background**
The current on-taskgraph log misses task and graph name, which makes developers hard to track workflow's actual behavior. It will be beneficial if adding their name into it. For more details, you can go to https://rackhd.atlassian.net/browse/RAC-5456

**Details**
In on-tasks repo, change the file lib/task-graph.js to add graphName in the function TaskGraph( ).
Jenkins depends on: https://github.com/RackHD/on-core/pull/285, https://github.com/RackHD/on-taskgraph/pull/263

**TestDone**
test it successfully on ubuntu 14.04.exsi vm

**Reviewer**
@iceiilin @pengz1

### CODE REVIEW

**Comment by iceiilin** [comment]
add to whitelist

**Comment by yaolingling** [comment]
test this please

**Comment by yaolingling** [comment]
test this please

**Comment by yaolingling** [comment]
test this please

**Comment by pengz1** [comment]
+1

**Pull request merged**
