### PR TITLE
Remove length and pattern check in set bmc credentials

### PR DESCRIPTION
**Pull request by keedya**
- variable assigned to this task are internal variables({{context.password}}),
  therefore checking patern or lenght is invalid in this situation

### CODE REVIEW

**Comment by keedya** [comment]
@RackHD/corecommitters 
@yyscamper @brianparry @zyoung51 @jlongever @uppalk1 @tannoa2

**Comment by benbp** [comment]
I'm a little confused by the commit message description. Does it mean we check the length elsewhere, or that it is impossible to check?

**Comment by benbp** [comment]
@keedya tells me that the password itself is set to `{{ context.password }}`, which then gets rendered at runtime.

👍

**Comment by yyscamper** [comment]
The task validation has already considered to skip context during upfront validation (https://github.com/RackHD/on-tasks/blob/master/lib/task.js#L434), this validation will only be done after this task is really scheduled. So at that time, the {{context.password}} has already been rendered and the validation will work well.

As for why I limit the password & username length, because this is defined in IPMI spec. If you want to know the detail, I can give you the particular section in spec.

So I don't think this is a problem due to task schema.
@keedya : could you please explain more for the issue you encountered?

At present, this PR is :-1

**Comment by yyscamper** [comment]
@keedya : this is the IPMI spec: http://www.intel.com/content/www/us/en/servers/ipmi/ipmi-second-gen-interface-spec-v2-rev1-1.html

The username is in Section 22.28 "Set User Name Command", the password is in Section "22.30 Set User Password Command"

**Comment by panpan0000** [comment]
Jenkins shows unit-test failure , please notify me if it's a false alarm, thank you.

**Comment by keedya** [comment]
@yyscamper validation is skipped in the beginning when task is called by id, the variable for password will be {{ context.password }}. This is a end variable that won't change unless it is rendered in a script

**Comment by keedya** [comment]
@yyscamper, this has nothing to do with the real password that we pass to ipmitool. I am aware of the bmc and ipmitool specs

**Comment by keedya** [comment]
@yyscamper  the failure is related to the encryption added in the following commit:
https://github.com/RackHD/on-core/commit/06638621b02727db77c57ad2493640b6b41806ab

I will open a github issue to track it
Closing this PR

**Pull request closed without merging**
