### PR TITLE
Issue#54: fix the wrong usage for chai-as-promise in unit-test

### PR DESCRIPTION
**Pull request by yyscamper**
This is part of fix for https://github.com/RackHD/RackHD/issues/54. You can get the detail information from issue.

@RackHD/corecommitters @WangWinson @iceiilin @pengz1 @sunnyqianzhang @cgx027

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by iceiilin** [comment]
What's the side effect if using eventually in this case?

**Comment by iceiilin** [comment]
+1

**Comment by WangWinson** [comment]
:+1:

**Comment by yyscamper** [comment]
Add change to other files according to @heckj 's comment in https://github.com/RackHD/RackHD/issues/54 .

Meanwhile, removed some unwanted space in local-catalog unit-test.

**Comment by heckj** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Pull request merged**
