### PR TITLE
Handle empty element member list

### PR DESCRIPTION
**Pull request by jlongever**
- Handle empty element list errors
- Convert MS encoding to Unix in `catalogSpine()` (`^M` cleanup)

@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya

### CODE REVIEW

**Comment by brianparry** [comment]
:+1:

**Comment by amymullins** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by rackhdmirror** [comment]
Build finished.

**Pull request merged**
