### PR TITLE
Rest catalog task/Job

### PR DESCRIPTION
**Pull request by nucklehead**
depends on: https://github.com/RackHD/on-core/pull/312
This PR adds a new tasks/job to update a node catalog based on a south bound rest api call.

This call could be to _Dell IDRAC_, _Cisco NXAPI_ or _on-network_.

This also fixes some dependencies and tests issues.

### CODE REVIEW

**Comment by mtannous** [comment]
@tannoa2 can you have a look at this

**Comment by keedya** [comment]
ok to test

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package-lock.json - package.json

**Comment by PengTian0** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package-lock.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package-lock.json

**Pull request merged**
