### PR TITLE
 Move http tool to on-core

### PR DESCRIPTION
**Pull request by pengz1**
Jenkins depends on: https://github.com/RackHD/on-core/pull/244
 * Hook design need http methods in on-core repo
 * To leverage those code, http-tool.js is moved to
   on-core/lib/common/http-tool.js
 * Documents requiring http-tool.js are updated accordingly

### CODE REVIEW

**Comment by pengz1** [comment]
@yyscamper @anhou @iceiilin @sunnyqianzhang @brianparry

**Comment by pengz1** [comment]
test this please

**Comment by pengz1** [comment]
Please ignore travis-ci failure as unit-test also depends on on-core PR RackHD/on-core#244.

**Comment by changev** [comment]
You have written dependency in on-core PR, so this PR needn't "test this please"

**Comment by iceiilin** [comment]
+1

**Comment by changev** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by sunnyqianzhang** [comment]
This PR looks good to me +1

**Comment by changev** [comment]
test this please

**Pull request merged**
