### PR TITLE
Redfish catalog of dell endpoint

### PR DESCRIPTION
**Pull request by srinia6**
Signed-off-by: Billy Abildgaard <william.abildgaardjr@emc.com>

Add Redfish catalog of dell Fans/PowerSupplies and Drives endpoint.

### CODE REVIEW

**Comment by geoff-reid** [comment]
Any idea what caused the drop in test coverage?

**Comment by srinia6** [comment]
@geoff-reid Guessing adding new file might have caused the change in %.

**Comment by srinia6** [comment]
jenkins: depends on https://github.com/RackHD/on-taskgraph/pull/254

**Comment by BillyAbildgaard** [comment]
jenkins, test this please

**Comment by srinia6** [comment]
Test this please

**Comment by srinia6** [comment]
test this please

**Pull request merged**
