### PR TITLE
Fix for RackHD Issue #304

### PR DESCRIPTION
**Pull request by brianparry**
* Change default OBM control job service to IPMI

Resolves https://github.com/RackHD/RackHD/issues/304

### CODE REVIEW

**Comment by brianparry** [comment]
@RackHD/corecommitters

**Comment by benbp** [comment]
@brianparry The intent of the existing code was if a node had a different obm-service defined, we wouldn't have to specify `obmServiceName` in the task definition. It looks like this removes that option, or am I misunderstanding?

**Comment by jlongever** [comment]
-1,  what @benbp said.

**Comment by brianparry** [comment]
@benbp @jlongever Agree.  I misunderstood what @jlongever was saying earlier.  I'm closing this PR.

**Pull request closed without merging**
