### PR TITLE
added tasks for cataloging installed packages

### PR DESCRIPTION
**Pull request by VulpesArtificem**
Added tasks to catalog the installed packages on a node
@RackHD/corecommitters

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by VulpesArtificem** [comment]
test this please

**Comment by yyscamper** [comment]
@VulpesArtificem , each task definition will map to a test case file, you just need to copy one and with minor modification.

:+1: after adding the unit-test.

**Comment by anhou** [comment]
:+1: with unit tests

**Comment by zyoung51** [comment]
@VulpesArtificem: What about adding one for esxi to catalog vib: 'esxcli --debug --formatter=json software vib list'

**Comment by VulpesArtificem** [comment]
@zyoung51 Yep, that will probably come as a follow-on work item/PR.

**Pull request merged**
