### PR TITLE
attempting to match the change from https://github.com/RackHD/RackHD/issues/32

### PR DESCRIPTION
**Pull request by heckj**
@tysonmcnulty @benbp I'm trying to match the change that you implemented locally to fix this issue. Is this what you changed?

### CODE REVIEW

**Comment by heckj** [comment]
thanks @tysonmcnulty, updated the PR

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
@VulpesArtificem

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Pull request merged**
