### PR TITLE
Fix ODR869: Rename the esx to ESXi for AnalyzeOsRepoJob

### PR DESCRIPTION
**Pull request by yyscamper**
Fix [ODR869](https://hwjiraprd01.corp.emc.com/browse/ODR-869) and take this chance to fix an outstanding rename work that stated in this issue: https://github.com/RackHD/RackHD/issues/218

@RackHD/corecommitters @gpaulos @cgx027 @pengz1 @iceiilin @WangWinson

### CODE REVIEW

**Comment by WangWinson** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by anhou** [comment]
@yyscamper  Do you know why Jenkins-Dependency-PR  fail?

**Comment by yyscamper** [comment]
@anhou : I have no idea why Jenkins-Dependency-PR fails. @changev: could you please help?

**Comment by changev** [comment]
@yyscamper @anhou I checked this build, actually no error occurs in jenkins test, but the xunit generate a error report from a success unit-test. So this may be a xunit issue, but not this PR.

This is a good PR passed all tests. You can merge it now.

**Comment by yyscamper** [comment]
Thanks @changev , please add an action item to follow up the jenkins problem.

**Pull request merged**
