### PR TITLE
persist ignore failure

### PR DESCRIPTION
**Pull request by VulpesArtificem**
fix for https://github.com/RackHD/RackHD/issues/327

requires
https://github.com/RackHD/on-taskgraph/pull/172
and 
https://github.com/RackHD/on-core/pull/213

@RackHD/corecommitters @pscharla

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by pscharla** [comment]
@RackHD/corecommitters: please review in the near term. This PR is blocking a couple P1 ODRs

**Comment by pscharla** [comment]
@RackHD/corecommitters : Checking with @panpan0000 again, but last I knew we can ignore the "Jenkins-Dependency-PR" failure. Please merge since this is blocking P1 ODR.

**Comment by johren** [comment]
Can this go in without https://github.com/RackHD/on-taskgraph/pull/172 or do we need +1s on that first?

**Pull request merged**
