### PR TITLE
Recreate sanitize fix for ODR-216

### PR DESCRIPTION
**Pull request by johren**
This recreates https://github.com/RackHD/on-tasks/pull/57 to add the fix for ODR-216 (which also addresses ODR-223) in the 1.0.0 branch.

### CODE REVIEW

**Comment by johren** [comment]
@benbp @VulpesArtificem

**Comment by benbp** [comment]
:+1:

**Comment by VulpesArtificem** [comment]
:+1:

**Comment by anhou** [comment]
:+1:  just a question, does it also need to be submitted to master branch?

**Comment by benbp** [comment]
@anhou it was a month or two ago. I closed the original 1.0 PR so this is a re-creation of that.

**Pull request merged**
