### PR TITLE
Tempory fix for issue 336 : Task.Snmp.Collect.Discovery in Graph.Switch.Discove…

### PR DESCRIPTION
**Pull request by manfrednde**
…ry fails with "maxBuffer exceeded"

Increased the amount of data allowed on stdout or stderr from 3MB to 6MB

@RackHD/corecommitters

### CODE REVIEW

**Comment by heckj** [comment]
👍 

fyi @amymullins since I think your gang was looking into how to make this more generally robust

**Comment by keedya** [comment]
@heckj , i was planning on recursively increase maxbuffer in case of "maxBuffer exceeded"

**Comment by johren** [comment]
@keedya, it is the snmpbulkwalk on a Cisco switch that hit this issue.  The output of the bulk walk as well as the logs are attached to https://github.com/RackHD/RackHD/issues/336

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by benbp** [comment]
👍

**Comment by benbp** [comment]
test this please

**Comment by jlongever** [comment]
downstream unit-tests failed..  test this please

**Comment by benbp** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by benbp** [comment]
test this plesae

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
http://10.240.19.21/job/on-tasks/1505/
seems the changes cause on-http and on-taskgraph errors

**Comment by changev** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Pull request merged**
