### PR TITLE
Adds Dockerfile for rackhd/on-tasks base image

### PR DESCRIPTION
**Pull request by rolandpoulter**
Create a base image similar to `rackhd/on-core` except that it includes `/RackHD/on-tasks` to make it so `rackhd/on-http` and `rackhd/on-taskgraph` can easily load custom versions of `on-tasks`. Currently it always loads the latest at `github@rackhd/on-tasks.git`.

This will make it easier to test on-tasks changes when running in docker.

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
👍

**Comment by heckj** [comment]
fyi @codenrhoden

**Comment by heckj** [comment]
👍

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Pull request closed without merging**
