### PR TITLE
Wipe nvram in flahsing Quanta BIOS task

### PR DESCRIPTION
**Pull request by iceiilin**
Partial fix of ODR 620 about failure in BIOS update. NVRAM structure might change among different BIOS versions. Change to /N to wipe nvram settings when updating.

### CODE REVIEW

**Comment by stuart-stanley** [comment]
@derrickostertag since he worked on this before, I believe. My concern: is the options file that is part of the payload a delta or a complete overwrite? If the former, this change would be a problem. If the latter, this is +1

**Comment by zyoung51** [comment]
+1

@stuart-stanley @derrickostertag I found this was a required step when upgrading/downgrading between 3A14 and newer versions.  While this could be skipped when upgrading/downgrading between 17, 18 and 19, skipping it when upgrading from 14 to a newer version or downgrading back to 14 from a newer version resulted in bricking the Quanta.

**Comment by yyscamper** [comment]
good :+1:

**Comment by stuart-stanley** [comment]
Still wondering if the options.file is a delta or a complete-set. If the former, I'm not sure this is a fix. If the latter, +1 no problem....

**Comment by derrickostertag** [comment]
If the nvram of the BIOS gets wiped, depending on the defaults settings, we may lose the ability to control or talk to the BMC until settings can be manually set. If this is what has to be done, we need to verify it and put in the release notes.

**Comment by iceiilin** [comment]
@stuart-stanley options.file is rendered completely by user's payload. I am not sure if I understand your concerns here.

**Comment by iceiilin** [comment]
@derrickostertag I downgrade BIOS from 3A18 to 3A16 with this wiping flag, and still can talk to BMC.

**Comment by derrickostertag** [comment]
@iceiilin Good. And going from 3A14 to 3A16+ BIOS settings are the same? if so +1

**Comment by stuart-stanley** [comment]
@iceiilin if the user is expecting the options.file that is downloaded to be a DELTA against the current config, wiping the nvram will reset a bunch of things they were NOT expecting to change.
If the options.file is always the *complete* set of config information, then there is no problem...

**Comment by zyoung51** [comment]
@stuart-stanley FWIW, its the preservation of the settings that actually causes it to be bricked.  The quanta procedure wipes the nvram to avoid this condition.

A user needs to provide a full file or expect non-deterministic behavior. The nvram utility does a full dump and it is expected that the user edits the settings they want changed and then provides that full file back.

**Comment by iceiilin** [comment]
test this please

**Pull request merged**
