### PR TITLE
updating slack notification for failure

### PR DESCRIPTION
**Pull request by tldavies**

### CODE REVIEW

**Comment by tldavies** [comment]
@benbp @heckj @zyoung51

**Comment by benbp** [comment]
:+1:

**Comment by zyoung51** [comment]
+1

**Comment by tldavies** [comment]
So we had a room that reported all builds on hipchat. Where is got all of the build status. I dont know if everyone ever really looked at it. As you can also go in travis to see the current status.

Im ok with changing success: changed. This means whenever it gets merged to master then we will get a travis update.

**Comment by benbp** [comment]
I'm worried that if we do success: changed, we'll get duplicate notifications for failure + success changed to failure?

**Comment by zyoung51** [comment]
+1

**Pull request merged**
