### PR TITLE
reverted file names to fit expected values by current example build p…

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
…rocess

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
@rolandpoulter @benbp @heckj

**Comment by benbp** [comment]
More context: match what we create with on-imagebuilder.

https://github.com/RackHD/on-imagebuilder/blob/6e5f6aa9a03d81559024584fbbf20ef711141d36/vars/discovery_overlay.yml
https://github.com/RackHD/on-imagebuilder/blob/6e5f6aa9a03d81559024584fbbf20ef711141d36/roles/overlay/build_overlay_archive/tasks/main.yml#L15
https://github.com/RackHD/on-imagebuilder/blob/master/group_vars/on_imagebuild#L23

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
@RackHD/corecommitters FYI here, this may cause breakage on people's environments if they are still using the on-static-common debian package files instead of the uploads to https://bintray.com/rackhd/binary/on-imagebuilder/view

**Comment by heckj** [comment]
+1

**Pull request merged**
