### PR TITLE
Add task to wait for a completion Uri trigger

### PR DESCRIPTION
**Pull request by zyoung51**
Add a task to wait for a Uri trigger to resolve an issue
with ESXi installation early completion.

### CODE REVIEW

**Comment by zyoung51** [comment]
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @jlongever

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
