### PR TITLE
Fix for failing functional tests.

### PR DESCRIPTION
**Pull request by brianparry**
* Force obms.findByNode to decrypt password by default.

### CODE REVIEW

**Comment by BillyAbildgaard** [comment]
+1

**Comment by srinia6** [comment]
+1

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by benbp** [comment]
👍 , though I'll also give a suggestion to, in general, pass in arguments like this as objects instead of boolean flags, so that it's easier to tell what you are setting (e.g. `return waterline.obms.findByNode(nodeId, 'redfish-obm-service', { reveal: true })`)

**Comment by brianparry** [comment]
Thanks @benbp.  I like your options object suggestion. I'll put together another PR with this change.

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this plesae

**Comment by brianparry** [comment]
test this please

**Comment by dalebremner** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by brianparry** [comment]
Jenkins failures are unrelated to this change.  Tests run locally, so merging.

**Pull request merged**
