### PR TITLE
ODR-547 use findOrCreate instead of create when creating default pollers

### PR DESCRIPTION
**Pull request by jimturnquist**
ODR-547 use findOrCreate instead of create when creating default pollers

Updated spec tests to account for switch from create to findOrCreate.

### CODE REVIEW

**Comment by heckj** [comment]
hound errors re: 'expect and sinon' are ignorable...

**Comment by heckj** [comment]
:+1:

**Comment by heckj** [comment]
Note for other reviewers: this effectively makes the createDefaultPollers task idempotent so that it can safely be called on a "rediscovery" workflows to refresh the catalogs for a node.

**Comment by yyscamper** [comment]
:+1:

**Comment by johren** [comment]
@RackHD/corecommitters

**Comment by jlongever** [comment]
Can ignore ^^ jenkins error... SDR format changed in master,  no smoke tests for 1.1.0 right now.
+1

**Pull request merged**
