### PR TITLE
notification API design refactor

### PR DESCRIPTION
**Pull request by cgx027**
This PR is depended by: https://github.com/RackHD/on-http/pull/410

### CODE REVIEW

**Comment by cgx027** [comment]
Remove WIP flag.

@RackHD/corecommitters @yyscamper @anhou @WangWinson

**Comment by yyscamper** [comment]
:+1:

**Comment by WangWinson** [comment]
:+1:

**Comment by panpan0000** [comment]
test this please

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by changev** [comment]
Jenkins: depends on https://github.com/RackHD/on-http/pull/410

**Comment by changev** [comment]
Jenkins: test this please

**Comment by changev** [comment]
Jenkins: test this please

**Comment by changev** [comment]
Jenkins: test this please

**Comment by changev** [comment]
Jenkins: test this please

**Comment by changev** [comment]
Jenkins: test this please

**Pull request merged**
