### PR TITLE
Feature/poller format changes 1.1

### PR DESCRIPTION
**Pull request by brianparry**
Same changes as https://github.com/RackHD/onserve/pull/115 but rebased onto the 1.1 release branch.

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by brianparry** [comment]
Oops - unit tests failed because the the IPMI parser was modified for lodash 3.

**Comment by brianparry** [comment]
Unit tests fixed now

**Comment by brianparry** [comment]
:-1: for now.  We will probably not include this change in 1.1.

**Pull request closed without merging**
